(function(){'use strict';
var A=document.getElementById('app'),toastEl=document.getElementById('toast'),invite=new URLSearchParams(location.search).get('invite'),CAL='week',poller=null,busy=false;
function toast(t){toastEl.textContent=t;toastEl.classList.add('on');setTimeout(function(){toastEl.classList.remove('on')},2200)}
function stopPoll(){if(poller){clearInterval(poller);poller=null}}
function startPoll(){stopPoll();poller=setInterval(function(){if(!document.hidden&&!busy&&DT.session())DT.refresh().then(function(r){if(r.changed)room()}).catch(function(){})},3500)}
function top(){var D=DT.state(),S=DT.session(),x='<div class="w"><header class="top"><button class="brand" data-a="home">◉ 대화틈</button>';if(D&&D.me){x+='<div class="people"><span class="av">'+DT.initial(D.me.name)+'</span><b>'+DT.esc(D.me.name)+' · 나</b>';if(D.partner)x+='<span>×</span><span class="av t">'+DT.initial(D.partner.name)+'</span><b>'+DT.esc(D.partner.name)+'</b>';x+='</div>'}if(S)x+='<button class="dots" data-a="settings">•••</button>';return x+'</header>'}
function end(){return'</div>'}
function spacesView(){var list=DT.spaces();if(!list.length)return'';var x='<section class="spaces"><h2>내 대화틈</h2>';list.slice().reverse().forEach(function(s){var pair=s.partnerName?DT.esc(s.name)+' × '+DT.esc(s.partnerName):DT.esc(s.name)+' · 초대 대기중',sub=s.partnerName?'이어지는 대화 '+(s.lastRound?('· ROUND '+String(s.lastRound).padStart(2,'0')):''):'상대방을 초대하면 시작돼요';x+='<section class="card spacecard"><div><span class="k">'+(s.partnerName?'TOGETHER':'WAITING')+'</span><h3>'+pair+'</h3><p>'+sub+'</p></div><button class="btn outline" data-a="open-room" data-room="'+DT.esc(s.room)+'">열기</button></section>'});return x+'<p class="c"><button class="text" data-a="new">새로운 대화틈 만들기</button></p></section>'}
function home(){stopPoll();DT.setState(null);var known=invite&&DT.findByInvite(invite);if(known){DT.activate(known.room);invite=null;DT.clearQuery();return loadRoom()}if(invite)return join();A.innerHTML=top()+'<section class="hero"><div><span class="k">A SMALL SPACE BETWEEN US</span><h1>말 사이에,<br><em>대화할 틈.</em></h1><p>같은 질문에 각자 답하고,<br>둘 다 준비됐을 때 함께 열어봐요.</p>'+(DT.spaces().length?'':'<button class="btn" data-a="create">대화틈 만들기 →</button>')+'<p style="font-size:11px">계정 없이 · 링크를 받은 두 사람만</p></div></section>'+spacesView()+end()}
function create(){stopPoll();A.innerHTML=top()+'<section class="card intro"><span class="k">먼저 나부터</span><h1>어떻게 불러드릴까요?</h1><p>상대방에게 보일 이름이에요. 이름 전체가 표시됩니다.</p><form class="form" id="cf"><label>내 이름</label><input name="name" maxlength="20" placeholder="예: 보람" required><button class="btn full">내 대화틈 만들기</button></form></section>'+end()}
function join(){stopPoll();var known=DT.findByInvite(invite);if(known){DT.activate(known.room);invite=null;DT.clearQuery();return loadRoom()}A.innerHTML=top()+'<section class="card intro"><span class="k">대화틈에 초대받았어요</span><h1>당신의 이름만 알려주세요.</h1><p>초대한 사람의 브라우저 정보는 이 링크로 넘어오지 않아요.</p><form class="form" id="jf"><label>내 이름</label><input name="name" maxlength="20" placeholder="예: 태원" required><button class="btn full">대화틈에 들어가기</button></form><button class="text" data-a="cancel">나중에 할게요</button></section>'+end()}
function hint(){var D=DT.state(),rev=DT.revealed();if(!D.partner)return'상대방이 들어오면 같은 질문이 보여요.';if(!D.me.answered)return DT.esc(D.partner.name)+'님의 답은 내가 답하기 전까지 보이지 않아요.';if(!D.partner.answered)return DT.esc(D.partner.name)+'님이 답하는 동안 내 답은 안전하게 보관돼요.';if(!rev)return'둘의 답이 모두 도착했어요. 준비되면 함께 열어봐요.';return'서로의 마음을 천천히 읽어보세요.'}
function calendarView(){var D=DT.state();if(!D||!D.partner)return'';var map={};(D.history||[]).forEach(function(x){var d=DT.dateObj(x.completed_at);if(d)map[DT.dayKey(d)]=1});var now=new Date(),days=[],count=0,title='',labels=['월','화','수','목','금','토','일'];if(CAL==='week'){var st=new Date(now.getFullYear(),now.getMonth(),now.getDate()),n=(st.getDay()+6)%7;st.setDate(st.getDate()-n);for(var i=0;i<7;i++){var d=new Date(st);d.setDate(st.getDate()+i);days.push(d)}title=(st.getMonth()+1)+'.'+st.getDate()+'–'+(days[6].getMonth()+1)+'.'+days[6].getDate()}else{var first=new Date(now.getFullYear(),now.getMonth(),1),last=new Date(now.getFullYear(),now.getMonth()+1,0),pad=(first.getDay()+6)%7;for(var p=0;p<pad;p++)days.push(null);for(var j=1;j<=last.getDate();j++)days.push(new Date(now.getFullYear(),now.getMonth(),j));title=(now.getMonth()+1)+'월'}var grid=days.map(function(d){if(!d)return'<span class="day blank"></span>';var k=DT.dayKey(d),done=!!map[k],today=k===DT.dayKey(now);if(done)count++;return'<span class="day '+(done?'done ':'')+(today?'today':'')+'"><small>'+(CAL==='week'?labels[(d.getDay()+6)%7]:'')+'</small><b>'+d.getDate()+'</b><i>✓</i></span>'}).join('');return'<section class="card cal"><div class="caltop"><div><span class="k">OUR RHYTHM · '+DT.esc(title)+'</span><h2>우리의 대화 리듬</h2><p>둘 다 답한 날이 채워져요.</p></div><div class="switch"><button data-a="cal-week" class="'+(CAL==='week'?'on':'')+'">주간</button><button data-a="cal-month" class="'+(CAL==='month'?'on':'')+'">월간</button></div></div>'+(CAL==='month'?'<div class="weekdays">'+labels.map(function(x){return'<span>'+x+'</span>'}).join('')+'</div>':'')+'<div class="'+(CAL==='week'?'weekgrid':'monthgrid')+'">'+grid+'</div><div class="calmeta">'+(CAL==='week'?'이번 주 ':'이번 달 ')+count+'일 채움</div></section>'}
function historyView(a){var D=DT.state(),x='<section class="hist"><h2>지난 대화 <small>'+a.length+'</small></h2>';a.forEach(function(y){var dl=DT.dateLabel(y.completed_at||y.created_at);x+='<details class="item"><summary>ROUND '+String(y.sequence||'').padStart(2,'0')+(dl?' · '+dl:'')+' · '+DT.esc(y.question)+'</summary><div class="hb"><div><small>'+DT.esc(D.me.name)+' · 나</small><p>'+DT.nl(y.me_answer)+'</p></div><div><small>'+DT.esc(D.partner?D.partner.name:'상대방')+'</small><p>'+DT.nl(y.partner_answer)+'</p></div></div></details>'});return x+'</section>'}
function room(){var D=DT.state(),rev=DT.revealed(),hist=(D.history||[]).filter(function(x){return x.round_id!==D.round_id||rev}),stage;if(!D.partner)stage='<section class="card stage c"><div class="orb"><i></i><i></i></div><span class="k">함께할 사람</span><h2>누구와 이 질문을 나눌까요?</h2><p>초대장을 보내면 상대방도 같은 질문에 답할 수 있어요.<br>카카오톡이나 문자로 바로 보낼 수 있어요.</p><button class="btn full" data-a="share">초대하기</button><button class="btn outline full" data-a="copy" style="margin-top:10px">링크 복사하기</button></section>';else if(!D.me.answered)stage='<section class="card stage"><div class="head"><span class="badge">나</span><b>'+DT.esc(D.me.name)+'</b><span class="badge lock">아직 비공개</span></div><form id="af"><textarea name="answer" maxlength="1000" placeholder="지금 떠오르는 마음을 적어보세요." required></textarea><p class="c"><button class="btn">내 답 보내기</button></p></form></section>';else if(!D.partner.answered)stage='<section class="card stage c"><div class="orb"><i></i><i></i></div><span class="k">내 답은 도착했어요</span><h2>'+DT.esc(D.partner.name)+'님의 답을 기다리는 중</h2><p>화면을 닫아도 다시 여기서 이어집니다.</p><details class="mine"><summary>내가 쓴 답 보기</summary><p>'+DT.nl(D.me.answer)+'</p></details></section>';else if(D.unlocked&&!rev)stage='<section class="card stage c"><div class="reveal"><span class="av">'+DT.initial(D.me.name)+'</span><i></i><span class="av t">'+DT.initial(D.partner.name)+'</span></div><span class="k">둘 다 답했어요</span><h2>이제 서로의 답을 열어볼까요?</h2><p>답을 보내자마자 갑자기 공개되지 않아요.</p><button class="btn full" data-a="reveal">서로의 답 열어보기</button></section>';else stage='<section><div class="c"><span class="k">OUR ANSWERS</span><h2>같은 질문, 두 개의 마음</h2></div><div class="answers"><article class="card ans me"><header><span class="av">'+DT.initial(D.me.name)+'</span><b>'+DT.esc(D.me.name)+' · 나</b></header><p>'+DT.nl(D.me.answer)+'</p></article><article class="card ans them"><header><span class="av t">'+DT.initial(D.partner.name)+'</span><b>'+DT.esc(D.partner.name)+'</b></header><p>'+DT.nl(D.partner.answer)+'</p></article></div><button class="btn outline full" data-a="next" style="margin-top:10px">다음 질문으로 →</button></section>';var dl=DT.dateLabel(D.round_created_at);A.innerHTML=top()+'<section class="q"><span class="k">ROUND '+String(D.round_sequence||1).padStart(2,'0')+(dl?' · '+dl:'')+'</span><h1>'+DT.esc(D.question)+'</h1><p>'+hint()+'</p></section>'+stage+calendarView()+(hist.length?historyView(hist):'')+'<div class="settings"><button class="text" data-a="settings">내 대화틈 보기</button></div>'+end();startPoll()}
function loadRoom(){busy=true;return DT.refresh().then(function(){room()}).catch(function(e){A.innerHTML=top()+'<section class="card stage c"><h2>대화틈을 불러오지 못했어요.</h2><p>'+DT.esc(e.message)+'</p><button class="btn full" data-a="settings">내 대화틈 보기</button></section>'+end()}).then(function(){busy=false},function(){busy=false})}
function submitCreate(f){if(busy)return;busy=true;var b=f.querySelector('button'),name=new FormData(f).get('name').trim();b.disabled=true;b.textContent='만드는 중…';DT.createRoom(name).then(function(){invite=null;DT.clearQuery();room()}).catch(function(e){toast(e.message);b.disabled=false;b.textContent='내 대화틈 만들기'}).then(function(){busy=false},function(){busy=false})}
function submitJoin(f){if(busy)return;busy=true;var b=f.querySelector('button'),name=new FormData(f).get('name').trim(),tok=invite;b.disabled=true;b.textContent='연결하는 중…';DT.joinRoom(tok,name).then(function(){invite=null;DT.clearQuery();room()}).catch(function(e){toast(e.message);b.disabled=false;b.textContent='대화틈에 들어가기'}).then(function(){busy=false},function(){busy=false})}
function submitAnswer(f){if(busy)return;busy=true;var b=f.querySelector('button'),v=new FormData(f).get('answer').trim();b.disabled=true;b.textContent='보내는 중…';DT.answer(v).then(room).catch(function(e){toast(e.message);b.disabled=false;b.textContent='내 답 보내기'}).then(function(){busy=false},function(){busy=false})}
function copy(){var u=DT.inviteUrl();if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(u).then(function(){toast('초대 링크를 복사했어요.')},function(){prompt('초대 링크를 복사해 주세요.',u)});else prompt('초대 링크를 복사해 주세요.',u)}
function share(){var u=DT.inviteUrl();if(navigator.share)navigator.share({title:'대화틈',text:'같은 질문에 각자 답하고 함께 열어보자.',url:u}).catch(function(){});else copy()}
function act(a,arg){if(a==='home')home();else if(a==='create')create();else if(a==='open-room'){DT.activate(arg);loadRoom()}else if(a==='copy')copy();else if(a==='share')share();else if(a==='cal-week'){CAL='week';room()}else if(a==='cal-month'){CAL='month';room()}else if(a==='reveal'){DT.reveal();room()}else if(a==='next'){if(busy)return;busy=true;DT.next().then(room).catch(function(e){toast(e.message)}).then(function(){busy=false},function(){busy=false})}else if(a==='settings'){stopPoll();DT.clearActive();home()}else if(a==='new'){DT.clearActive();create()}else if(a==='cancel'){invite=null;DT.clearQuery();home()}}
A.addEventListener('click',function(ev){var b=ev.target.closest('[data-a]');if(b){ev.preventDefault();act(b.getAttribute('data-a'),b.getAttribute('data-room'))}});
A.addEventListener('submit',function(ev){ev.preventDefault();if(ev.target.id==='cf')submitCreate(ev.target);else if(ev.target.id==='jf')submitJoin(ev.target);else if(ev.target.id==='af')submitAnswer(ev.target)});
document.addEventListener('visibilitychange',function(){if(!document.hidden&&DT.session()&&DT.state())DT.refresh().then(function(r){if(r.changed)room()}).catch(function(){})});
var start=document.getElementById('start');if(start)start.onclick=create;if(invite){var known=DT.findByInvite(invite);if(known){DT.activate(known.room);invite=null;DT.clearQuery();loadRoom()}else join()}else home();
})();
