(function(){'use strict';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
var checkedInvite={};
function txt(koText,enText){return ko?koText:enText}
function esc(v){return window.DT&&DT.esc?DT.esc(v):String(v||'')}
function patchCreate(){var f=document.getElementById('cf');if(!f||f.querySelector('.capacity-block'))return;var rel=f.querySelector('.rel-grid');if(!rel)return;var premium=DT.isPremium();var html='<div class="capacity-block"><div class="capacity-title"><b>'+txt('몇 명이 함께할까요?','How many people will join?')+'</b><small>'+txt('나 포함','including you')+'</small></div><div class="capacity-grid">';[2,3,4,5].forEach(function(n){html+='<label class="capacity-option"><input type="radio" name="target" value="'+n+'" '+(n===2?'checked':'')+'><span>'+n+txt('명','')+((n>2&&!premium)?'<small>★ Premium</small>':'')+'</span></label>'});html+='</div><p class="capacity-note" id="capacity-note">'+txt('선택한 인원이 모두 들어오면 첫 질문을 시작해요.','The first question starts when everyone has joined.')+'</p></div>';rel.insertAdjacentHTML('afterend',html);f.querySelectorAll('input[name="target"]').forEach(function(r){r.addEventListener('change',function(){var n=parseInt(r.value,10),note=document.getElementById('capacity-note');if(note)note.textContent=n>2&&!DT.isPremium()?txt(n+'명 이상은 Premium 기능이에요. Beta에서는 결제 없이 바로 열 수 있어요.',n+'+ people is a Premium feature. Beta unlocks it without payment.'):txt('선택한 인원이 모두 들어오면 첫 질문을 시작해요.','The first question starts when everyone has joined.')})})}
function modal(form,target){if(document.querySelector('.capacity-upgrade'))return;var m=document.createElement('div');m.className='capacity-upgrade';m.innerHTML='<section class="capacity-upgrade-card"><span class="k">PREMIUM</span><h2>'+txt(target+'명이 함께하는 대화틈','A '+target+'-person space')+'</h2><p>'+txt('3명 이상 대화는 Premium 기능이에요. Beta에서는 실제 결제 없이 바로 활성화됩니다.','Spaces with 3+ people are Premium. In beta, it unlocks immediately with no payment.')+'</p><button class="btn full" id="cap-upgrade">'+txt('Premium으로 열기','Unlock Premium')+'</button><button class="text" id="cap-cancel">'+txt('2명으로 할게요','Keep it to 2 people')+'</button></section>';document.body.appendChild(m);m.querySelector('#cap-upgrade').onclick=function(){DT.setPremium(true);m.remove();window.DT_CREATE_TARGET=target;form.requestSubmit()};m.querySelector('#cap-cancel').onclick=function(){var two=form.querySelector('input[name="target"][value="2"]');if(two)two.checked=true;m.remove()}}
function inviteActivity(){var D=DT.state(),S=DT.session();if(!D||!S||!D.me||!D.me.is_creator||S.inviteSentAt||checkedInvite[S.room])return;checkedInvite[S.room]=1;fetch('https://kacvynoegfpvgdpqtjdi.supabase.co/rest/v1/rpc/dt_get_invite_activity',{method:'POST',headers:{apikey:'sb_publishable_SeG92zfrAeh5zECaVbztkw_qb0C91D6','Content-Type':'application/json'},body:JSON.stringify({p_room_id:S.room,p_participant_token:S.token})}).then(function(r){return r.ok?r.json():null}).then(function(x){if(x&&x.sent){S.inviteSentAt=x.last_sent_at||new Date().toISOString();DT.saveSession(S);patchRoom()}}).catch(function(){})}
function waitCard(D){var target=parseInt(D.max_participants||2,10),count=parseInt(D.participant_count||1,10),remain=Math.max(0,target-count),sent=DT.inviteWasSent&&DT.inviteWasSent(),title,body;if(count>1){title=txt(target+'명 중 '+count+'명이 모였어요',count+' of '+target+' people are here');body=txt(remain===1?'한 명만 더 들어오면 시작해요.':remain+'명만 더 들어오면 시작해요.',remain===1?'One more person and you can start.':remain+' more people and you can start.')}else if(sent){title=txt('초대장을 보냈어요','Invite sent');body=txt(target+'명 중 1명이 준비됐어요. '+remain+'명이 들어오면 시작해요.','1 of '+target+' is ready. Start when '+remain+' more join.')}else{title=txt('누구와 이 7일을 나눌까요?','Who will share these 7 days?');body=txt('총 '+target+'명이 함께하는 방이에요. '+remain+'명에게 초대장을 보내주세요.','This space is for '+target+' people. Invite '+remain+' more.')}var dots='';for(var i=0;i<target;i++)dots+='<i class="'+(i<count?'on':'')+'"></i>';return'<section class="card stage c capacity-wait" data-capacity-state="'+count+'-'+target+'-'+(sent?1:0)+'"><div class="capacity-progress">'+dots+'</div><span class="k">'+txt('초대 대기','WAITING FOR PEOPLE')+'</span><h2>'+esc(title)+'</h2><p class="countline">'+count+' / '+target+'</p><p>'+esc(body)+'</p><button class="btn full" data-a="share">'+(sent?txt('다시 초대하기','Invite again'):txt('초대하기','Invite'))+'</button><button class="btn outline full" data-a="copy">'+txt('링크 복사하기','Copy link')+'</button></section>'}
function patchRoom(){if(!window.DT)return;var D=DT.state();if(!D)return;var q=document.querySelector('.q');if(!q)return;var target=parseInt(D.max_participants||2,10),count=parseInt(D.participant_count||0,10);if(count<target){inviteActivity();var stage=q.nextElementSibling;if(stage){var wanted=count+'-'+target+'-'+((DT.inviteWasSent&&DT.inviteWasSent())?1:0);if(stage.getAttribute('data-capacity-state')!==wanted)stage.outerHTML=waitCard(D)}document.querySelectorAll('.premium-tools,.cal,.hist').forEach(function(el){el.style.display='none'})}else{document.querySelectorAll('.premium-tools,.cal,.hist').forEach(function(el){el.style.display=''})}}
function patch(){patchCreate();patchRoom()}
document.addEventListener('submit',function(e){if(e.target&&e.target.id==='cf'){var r=e.target.querySelector('input[name="target"]:checked'),target=parseInt(r?r.value:2,10);window.DT_CREATE_TARGET=target;if(target>2&&!DT.isPremium()){e.preventDefault();e.stopImmediatePropagation();modal(e.target,target)}}},true);
document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('[data-a]');if(!b)return;var a=b.getAttribute('data-a');if((a==='share'||a==='copy')&&DT.state()&&DT.state().participant_count<DT.state().max_participants){if(DT.markInviteSent)DT.markInviteSent();setTimeout(patchRoom,120)}},true);
new MutationObserver(function(){setTimeout(patch,0)}).observe(document.getElementById('app'),{childList:true,subtree:true});
setTimeout(patch,80);
})();