(function(){'use strict';
var patched=false,ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
function patchState(){if(patched||!window.DT||!DT.state)return;var original=DT.state;DT.state=function(){var d=original();if(d&&d.is_premium&&(d.round_sequence||0)>7)d.challenge_complete=false;return d};patched=true}
function copy(){return ko?{done:'7일의 대화가 완성됐어요',body:'Premium에서는 이 방을 그대로 이어갈 수 있어요. 지난 기록은 남겨두고, 다음 질문부터 계속 쌓아가요.',cta:'Premium으로 계속하기',beta:'Private Beta에서는 결제 없이 바로 활성화됩니다.',host:'방을 만든 사람이 Premium을 활성화하면 이 대화를 계속 이어갈 수 있어요.',wait:'다음 질문을 준비하고 있어요.',reserve:'✎ 질문 예약하기',reserveSub:'떠오른 질문을 미리 남겨두세요.'}:{done:'Your first 7 days are complete',body:'With Premium, this same space can keep going. Your history stays here and new conversations keep building.',cta:'Continue with Premium',beta:'Premium unlocks without payment during the private beta.',host:'The room creator can activate Premium to keep this conversation going.',wait:'Getting the next question ready.',reserve:'✎ Reserve a question',reserveSub:'Leave a question whenever it comes to mind.'}}
function patchLabels(){var d=window.DT&&DT.state&&DT.state();if(!d)return;var q=document.querySelector('.q>.k');if(q&&(d.round_sequence||0)>7&&/^DAY\s+\d+\s+OF\s+7/i.test(q.textContent))q.textContent=q.textContent.replace(/^DAY\s+\d+\s+OF\s+7/i,'ROUND '+d.round_sequence);document.querySelectorAll('.spacecard p').forEach(function(p){var m=p.textContent.match(/^DAY\s+(\d+)/i);if(m&&parseInt(m[1],10)>7)p.textContent='ROUND '+m[1]})}
function ensureReserve(d){if(!d.is_premium||!document.querySelector('.q')||document.querySelector('[data-a="custom"]'))return;var grid=document.querySelector('.premium-tools .feature-grid');if(!grid)return;var c=copy(),b=document.createElement('button');b.className='feature';b.setAttribute('data-a','custom');b.innerHTML='<b>'+c.reserve+'</b><small>'+c.reserveSub+'</small>';grid.prepend(b)}
function ensurePremiumNext(d){if(!d.is_premium||d.round_sequence!==7||!d.challenge_complete||!d.reflection||!d.reflection.unlocked||!DT.revealed())return;if(document.querySelector('.next-gate')||document.querySelector('.schedule-open'))return;var c=copy(),sec=document.createElement('section');sec.className='card stage c next-gate';sec.innerHTML='<span class="k">PREMIUM · CONTINUE</span><h2>'+c.wait+'</h2><p></p>';var ref=document.querySelector('#extension-offer')||document.querySelector('.cal')||document.querySelector('.premium-tools');if(ref&&ref.parentNode)ref.parentNode.insertBefore(sec,ref);else{var w=document.querySelector('.w');if(w)w.appendChild(sec)}}
function ensureFreeOffer(d){var old=document.getElementById('extension-offer');if(d.is_premium){if(old)old.remove();return}if(!d.challenge_complete||d.round_sequence!==7||!d.reflection||!d.reflection.unlocked||!DT.revealed()){if(old)old.remove();return}if(old)return;var c=copy(),sec=document.createElement('section');sec.id='extension-offer';sec.className='card stage c premium-card';var creator=d.me&&d.me.is_creator;sec.innerHTML='<span class="k">PREMIUM · KEEP GOING</span><h2>'+c.done+'</h2><p>'+c.body+'</p>'+(creator?'<button class="btn full" id="continue-premium">'+c.cta+'</button><p style="font-size:10px">'+c.beta+'</p>':'<p class="premium-note">'+c.host+'</p>');var w=document.querySelector('.w');if(w)w.appendChild(sec);if(window.DT&&DT.log)DT.log('premium_continuation_view',{round:7,creator:!!creator});var btn=document.getElementById('continue-premium');if(btn)btn.onclick=function(){btn.disabled=true;if(window.DT&&DT.log)DT.log('premium_continuation_click',{round:7});DT.enablePremium().then(function(){location.reload()}).catch(function(e){btn.disabled=false;alert(e.message)})}}
function render(){patchState();if(!window.DT||!DT.state)return;var d=DT.state();if(!d)return;patchLabels();ensureReserve(d);ensureFreeOffer(d);ensurePremiumNext(d)}
function start(){patchState();var app=document.getElementById('app');if(app)new MutationObserver(function(){requestAnimationFrame(render)}).observe(app,{childList:true,subtree:true});setTimeout(render,0);document.addEventListener('visibilitychange',function(){if(!document.hidden)render()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
