(function(){'use strict';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0,patching=false;
function state(){return window.DT&&DT.state&&DT.state()}
function label(){return ko?'방장':'Host'}
function hostOf(D){var ps=(D&&D.participants)||[];for(var i=0;i<ps.length;i++)if(Number(ps[i].seat)===1)return ps[i];if(D&&D.me&&D.me.is_creator)return{name:D.me.name,seat:1,is_me:true};return null}
function addBadge(el){if(!el||el.querySelector('.host-badge'))return;var b=document.createElement('span');b.className='host-badge';b.textContent=label();el.appendChild(b)}
function cleanupLegacy(meta){if(!meta)return;meta.removeAttribute('data-room-host');meta.querySelectorAll('.room-host-meta').forEach(function(el){var prev=el.previousSibling;if(prev&&prev.nodeType===3&&/^\s*·\s*$/.test(prev.nodeValue||''))prev.remove();el.remove()})}
function patchMeta(D,host){var q=document.querySelector('.q'),meta=q&&q.querySelector(':scope > .k');if(!q||!meta||!host)return;cleanupLegacy(meta);var sig=label()+':'+host.name,line=q.querySelector(':scope > .room-host-line');if(line&&line.getAttribute('data-host-sig')===sig)return;if(!line){line=document.createElement('p');line.className='room-host-line';meta.insertAdjacentElement('afterend',line)}line.setAttribute('data-host-sig',sig);line.innerHTML='<span class="host-badge">'+label()+'</span><b></b>';line.querySelector('b').textContent=host.name}
function patchAvatars(D){var ps=(D&&D.participants)||[];document.querySelectorAll('.top .people .av').forEach(function(av,i){var p=ps[i],isHost=!!p&&Number(p.seat)===1;av.classList.toggle('host-avatar',isHost);if(isHost){av.setAttribute('data-host',label());av.setAttribute('title',label()+' · '+p.name)}else{av.removeAttribute('data-host');av.removeAttribute('title')}});document.querySelectorAll('.reveal.group-reveal .av').forEach(function(av,i){var p=ps[i],isHost=!!p&&Number(p.seat)===1;av.classList.toggle('host-avatar',isHost);if(isHost)av.setAttribute('data-host',label());else av.removeAttribute('data-host')})}
function patchNames(D,host){if(!host)return;var head=document.querySelector('.stage .head');if(head&&D.me&&D.me.is_creator)addBadge(head);document.querySelectorAll('.answers.group-answers').forEach(function(group){var cards=group.querySelectorAll(':scope > article.ans'),ps=(D.participants||[]);if(cards.length!==ps.length)return;cards.forEach(function(card,i){if(Number(ps[i].seat)!==1)return;var h=card.querySelector('header b')||card.querySelector(':scope > b');addBadge(h||card)})})}
function patch(){if(patching)return;patching=true;requestAnimationFrame(function(){patching=false;var D=state();if(!D||!D.me||!document.querySelector('.q'))return;var host=hostOf(D);patchMeta(D,host);patchAvatars(D);patchNames(D,host)})}
function start(){var app=document.getElementById('app');if(app)new MutationObserver(patch).observe(app,{childList:true,subtree:true});patch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();