(function(){'use strict';
var SUPA='https://kacvynoegfpvgdpqtjdi.supabase.co';
var KEY='sb_publishable_SeG92zfrAeh5zECaVbztkw_qb0C91D6';
var VAPID='BHUOF7L_UqRCa0mu_wHbVoVd-atKRuxUEXzNeSp5h8vqiD18ddCFu1XIs574wmN-DUnH3QyNoRerR9quHY8Rz8g';
var ENABLED='dt.push.enabled.v1',DISMISSED='dt.push.dismissed.v1',IOS_HINT='dt.push.ioshint.v1';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
var nativeApp=/DaehwateumAndroid/.test(navigator.userAgent);
function rpc(fn,payload){return fetch(SUPA+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.text().then(function(t){var j=null;try{j=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw Error(j&&j.message?j.message:'Push registration failed.');return j})})}
function b64ToUint8(s){var pad='='.repeat((4-s.length%4)%4),b=(s+pad).replace(/-/g,'+').replace(/_/g,'/'),raw=atob(b),out=new Uint8Array(raw.length);for(var i=0;i<raw.length;i++)out[i]=raw.charCodeAt(i);return out}
function standalone(){return window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone===true}
function isIOS(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1}
function supported(){return !nativeApp&&'serviceWorker'in navigator&&'PushManager'in window&&'Notification'in window}
function session(){return window.DT&&DT.session?DT.session():null}
function state(){return window.DT&&DT.state?DT.state():null}
function registerOnServer(sub){var s=session();if(!s||!s.room||!s.token)return Promise.reject(Error('No active conversation.'));return rpc('dt_register_push_device_v2',{p_room_id:s.room,p_participant_token:s.token,p_push_token:JSON.stringify(sub),p_platform:isIOS()?'ios':'web',p_locale:navigator.language||'ko'}).then(function(x){try{localStorage.setItem(ENABLED,'1');localStorage.removeItem(DISMISSED)}catch(e){}return x})}
function syncExisting(){if(!supported()||Notification.permission!=='granted')return Promise.resolve(false);return navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(){return navigator.serviceWorker.ready}).then(function(reg){return reg.pushManager.getSubscription().then(function(sub){if(!sub)return false;return registerOnServer(sub).then(function(){return true})})}).catch(function(){return false})}
function enable(){return navigator.serviceWorker.register('./sw.js',{scope:'./'}).then(function(){return Notification.requestPermission()}).then(function(permission){if(permission!=='granted')throw Error(ko?'알림 권한이 허용되지 않았어요.':'Notifications were not allowed.');return navigator.serviceWorker.ready}).then(function(reg){return reg.pushManager.getSubscription().then(function(existing){return existing||reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:b64ToUint8(VAPID)})})}).then(registerOnServer)}
function removePrompt(){var el=document.querySelector('.dt-notify-prompt');if(el)el.remove()}
function dismissed(){try{return localStorage.getItem(DISMISSED)==='1'}catch(e){return false}}
function markDismissed(){try{localStorage.setItem(DISMISSED,'1')}catch(e){}}
function iosHinted(){try{return localStorage.getItem(IOS_HINT)==='1'}catch(e){return false}}
function markIOSHinted(){try{localStorage.setItem(IOS_HINT,'1')}catch(e){}}
function promptCopy(reason){if(reason==='invite')return ko?['상대가 들어오면 알려드릴까요?','초대한 사람이 들어오거나 새로운 질문과 답이 준비되면 알려드릴게요.']:['Know when they join?','We’ll let you know when they join and when a new question or answers are ready.'];return ko?['다음 대화가 준비되면 알려드릴까요?','새로운 질문이 열리거나 서로의 답을 볼 수 있게 되면 알려드릴게요.']:['Know when the next conversation is ready?','We’ll let you know when a new question opens or your answers are ready to view.']}
function showPrompt(reason){if(nativeApp||document.querySelector('.dt-notify-prompt'))return;if(dismissed())return;if(isIOS()&&!standalone()){if(iosHinted())return;var hint=document.createElement('aside');hint.className='dt-notify-prompt';hint.innerHTML='<h3>'+(ko?'iPhone에서 알림 받기':'Get notifications on iPhone')+'</h3><p>'+(ko?'Safari의 공유 버튼에서 ‘홈 화면에 추가’를 한 뒤 대화틈을 열면 알림을 켤 수 있어요.':'Add Daehwateum to your Home Screen from Safari, then open it there to enable notifications.')+'</p><div class="dt-notify-actions"><button class="secondary" data-dt-push-later>'+(ko?'나중에':'Later')+'</button><button class="primary" data-dt-push-ok>'+(ko?'알겠어요':'Got it')+'</button></div>';document.body.appendChild(hint);hint.querySelector('[data-dt-push-ok]').onclick=function(){markIOSHinted();removePrompt()};hint.querySelector('[data-dt-push-later]').onclick=function(){markIOSHinted();removePrompt()};return}
if(!supported()||Notification.permission==='denied')return;if(Notification.permission==='granted'){syncExisting();return}var c=promptCopy(reason),el=document.createElement('aside');el.className='dt-notify-prompt';el.innerHTML='<h3>'+c[0]+'</h3><p>'+c[1]+'</p><div class="dt-notify-actions"><button class="secondary" data-dt-push-later>'+(ko?'나중에':'Later')+'</button><button class="primary" data-dt-push-enable>'+(ko?'알림 받기':'Enable notifications')+'</button></div>';document.body.appendChild(el);el.querySelector('[data-dt-push-later]').onclick=function(){markDismissed();removePrompt()};el.querySelector('[data-dt-push-enable]').onclick=function(){var b=this;b.disabled=true;b.textContent=ko?'켜는 중…':'Enabling…';enable().then(function(){removePrompt();liveBanner(ko?'알림을 켰어요.':'Notifications are on.')}).catch(function(err){b.disabled=false;b.textContent=ko?'알림 받기':'Enable notifications';liveBanner(err.message||'Notification setup failed.')})}}
var bannerTimer=null;function liveBanner(msg){var el=document.querySelector('.dt-live-banner');if(!el){el=document.createElement('aside');el.className='dt-live-banner';el.innerHTML='<b></b><button aria-label="Close">×</button>';document.body.appendChild(el);el.querySelector('button').onclick=function(){el.classList.remove('on')}}el.querySelector('b').textContent=msg;el.classList.add('on');clearTimeout(bannerTimer);bannerTimer=setTimeout(function(){el.classList.remove('on')},5000)}
function snap(D){if(!D)return null;var ps=D.participants||[];return{round:D.round_id||null,count:Number(D.participant_count||ps.length||0),all:ps.length>=2&&ps.every(function(p){return !!p.answered}),names:ps.filter(function(p){return !p.is_me}).map(function(p){return p.name})}}
function detect(before,after){if(!before||!after)return;if(after.count>before.count){var names=(after.names||[]).filter(function(n){return before.names.indexOf(n)<0});liveBanner(ko?(names.length?names[names.length-1]+'님이 대화틈에 들어왔어요 👋':'초대한 사람이 대화틈에 들어왔어요 👋'):'Someone joined your Daehwateum 👋');return}if(before.round&&after.round&&before.round!==after.round){liveBanner(ko?'새로운 질문이 열렸어요 💬':'A new question is ready 💬');return}if(!before.all&&after.all){liveBanner(ko?'🔓 상대방도 답했어요. 답변을 열어볼까요?':'🔓 Everyone answered. Ready to open the answers?')}}
function install(){if(!window.DT){setTimeout(install,30);return}var oldRefresh=DT.refresh;if(oldRefresh&&!oldRefresh.__dtPushWrapped){var wrapped=function(){var before=snap(state());return oldRefresh.apply(DT,arguments).then(function(r){detect(before,snap(state()));return r})};wrapped.__dtPushWrapped=true;DT.refresh=wrapped}var oldInvite=DT.markInviteSent;if(oldInvite&&!oldInvite.__dtPushWrapped){var wi=function(){var r=oldInvite.apply(DT,arguments);setTimeout(function(){showPrompt('invite')},450);return r};wi.__dtPushWrapped=true;DT.markInviteSent=wi}var oldJoin=DT.joinRoom;if(oldJoin&&!oldJoin.__dtPushWrapped){var wj=function(){return oldJoin.apply(DT,arguments).then(function(r){setTimeout(function(){showPrompt('join')},650);return r})};wj.__dtPushWrapped=true;DT.joinRoom=wj}var oldAnswer=DT.answer;if(oldAnswer&&!oldAnswer.__dtPushWrapped){var wa=function(){return oldAnswer.apply(DT,arguments).then(function(r){setTimeout(function(){showPrompt('answer')},650);return r})};wa.__dtPushWrapped=true;DT.answer=wa}setTimeout(syncExisting,900)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();