(function(){'use strict';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
function txt(k,e){return ko?k:e}
function esc(v){return window.DT&&DT.esc?DT.esc(v):String(v||'')}
function closeSheet(){var s=document.querySelector('.people-sheet');if(s)s.remove();document.body.classList.remove('people-sheet-open')}
function synthetic(action,feature){var app=document.getElementById('app');if(!app)return;var b=document.createElement('button');b.type='button';b.style.display='none';b.setAttribute('data-a',action);if(feature)b.setAttribute('data-feature',feature);app.appendChild(b);b.click();b.remove()}
function openSheet(){var D=window.DT&&DT.state&&DT.state();if(!D||!D.participants)return;closeSheet();var canInvite=!!(D.me&&D.me.is_creator&&D.can_invite_more),count=parseInt(D.participant_count||D.participants.length||0,10),rows=(D.participants||[]).map(function(p){return'<div class="people-row"><span class="av '+(p.is_me?'':'t')+'">'+(window.DT&&DT.initial?DT.initial(p.name):esc(String(p.name||'?').charAt(0)))+'</span><b>'+esc(p.name)+'</b>'+(p.is_me?'<span class="people-me">'+txt('나','Me')+'</span>':'')+'</div>'}).join('');var action='';if(canInvite){action='<button class="btn full" id="people-invite">+ '+txt('한 명 더 초대하기','Invite one more person')+'</button>'}else if(D.is_premium&&count>=5){action='<p class="people-sheet-note">'+txt('5명이 모두 들어왔어요.','All 5 spots are filled.')+'</p>'}var s=document.createElement('div');s.className='people-sheet';s.innerHTML='<section class="people-sheet-card" role="dialog" aria-modal="true" aria-label="'+txt('함께하는 사람','People in this space')+'"><div class="people-sheet-head"><h2>'+txt('함께하는 사람','People in this space')+'</h2><button class="people-sheet-close" type="button" aria-label="'+txt('닫기','Close')+'">×</button></div><p class="people-sheet-meta">'+count+txt('명이 함께하고 있어요.',' people are here.')+'</p><div class="people-list">'+rows+'</div>'+action+'</section>';document.body.appendChild(s);document.body.classList.add('people-sheet-open');s.addEventListener('click',function(e){if(e.target===s||e.target.closest('.people-sheet-close'))closeSheet()});var invite=s.querySelector('#people-invite');if(invite)invite.onclick=function(){closeSheet();synthetic('share')};}
function patchHeader(){var D=window.DT&&DT.state&&DT.state(),people=document.querySelector('.top .people');if(!D||!people||parseInt(D.participant_count||0,10)<2)return;people.setAttribute('data-people-manage','1');people.setAttribute('role','button');people.setAttribute('tabindex','0');people.setAttribute('aria-label',txt('함께하는 사람 보기','View people in this space'));if(D.me&&D.me.is_creator&&D.can_invite_more&&!document.querySelector('.top .people-plus')){var plus=document.createElement('button');plus.type='button';plus.className='people-plus';plus.setAttribute('aria-label',txt('한 명 더 초대하기','Invite one more person'));plus.textContent='+';people.insertAdjacentElement('afterend',plus)}}
document.addEventListener('click',function(e){if(e.target.closest('.top .people[data-people-manage],.top .people-plus')){e.preventDefault();openSheet()}},true);
document.addEventListener('keydown',function(e){if(e.key==='Escape')closeSheet();var p=e.target.closest&&e.target.closest('.top .people[data-people-manage]');if(p&&(e.key==='Enter'||e.key===' ')){e.preventDefault();openSheet()}});
new MutationObserver(function(){patchHeader()}).observe(document.getElementById('app'),{childList:true,subtree:true});
setTimeout(patchHeader,0);
})();