(function(){'use strict';
var SUPA='https://kacvynoegfpvgdpqtjdi.supabase.co';
var KEY='sb_publishable_SeG92zfrAeh5zECaVbztkw_qb0C91D6';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
var binding=false,recovering=false;
function txt(k,e){return ko?k:e}
function rpc(fn,payload){return fetch(SUPA+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(payload||{})}).then(function(r){return r.text().then(function(t){var j=null;try{j=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw Error(j&&j.message?j.message:txt('복구 중 문제가 생겼어요.','Recovery failed.'));return j})})}
function deviceId(){try{return window.AndroidDevice&&AndroidDevice.getId?String(AndroidDevice.getId()||''):''}catch(e){return''}}
function saveItems(items){if(!Array.isArray(items)||!items.length)return false;items.forEach(function(x){DT.saveSession({room:x.room_id,token:x.participant_token,invite:x.invite_token||undefined,name:x.name,relationshipType:x.relationship_type||'partner',isPremium:!!x.is_premium,rev:[]});if(x.seat===1&&x.is_premium)DT.setPremium(true)});DT.activate(items[0].room_id);return true}
function bindExisting(){if(binding||!window.DT)return;var did=deviceId(),spaces=DT.spaces();if(!did||!spaces.length)return;binding=true;Promise.all(spaces.filter(function(s){return s.room&&s.token}).map(function(s){return rpc('dt_bind_device',{p_room_id:s.room,p_participant_token:s.token,p_device_id:did}).catch(function(){return false})})).finally(function(){binding=false})}
function autoRecover(){if(recovering||!window.DT||DT.spaces().length)return;var did=deviceId();if(!did)return;recovering=true;rpc('dt_recover_device',{p_device_id:did}).then(function(items){if(saveItems(items))location.reload()}).catch(function(){}).finally(function(){recovering=false})}
function modal(){if(document.querySelector('.recovery-modal'))return;var m=document.createElement('div');m.className='recovery-modal';m.innerHTML='<section class="recovery-card"><span class="k">RECOVERY</span><h2>'+txt('이전 대화를 다시 찾을까요?','Restore your past conversations?')+'</h2><p>'+txt('앱을 다시 설치한 경우 복구 코드로 기존 자리와 답변을 되찾을 수 있어요.','If you reinstalled the app, use a recovery code to restore your rooms and answers.')+'</p><form id="recover-form"><input name="code" maxlength="20" autocomplete="off" autocapitalize="characters" placeholder="'+txt('복구 코드','Recovery code')+'" required><button class="btn full">'+txt('내 대화 복구하기','Restore my conversations')+'</button></form><button class="text" id="recover-cancel">'+txt('취소','Cancel')+'</button><p class="recovery-msg" id="recovery-msg"></p></section>';document.body.appendChild(m);m.querySelector('#recover-cancel').onclick=function(){m.remove()};m.querySelector('#recover-form').onsubmit=function(e){e.preventDefault();var code=(new FormData(e.target).get('code')||'').trim().toUpperCase(),msg=m.querySelector('#recovery-msg'),btn=e.target.querySelector('button');if(!code)return;btn.disabled=true;msg.textContent=txt('복구하는 중…','Restoring…');rpc('dt_recover_claim',{p_code:code,p_device_id:deviceId()||null}).then(function(items){if(!saveItems(items))throw Error(txt('복구할 대화를 찾지 못했어요.','No conversations were found.'));msg.textContent=txt(items.length+'개의 대화틈을 복구했어요.','Restored '+items.length+' conversation spaces.');setTimeout(function(){location.reload()},500)}).catch(function(err){msg.textContent=err.message;btn.disabled=false})}}
function inject(){if(!window.DT)return;bindExisting();autoRecover();if(document.querySelector('[data-recovery-entry]'))return;var closed=document.querySelector('.invite-closed');var host=closed||document.querySelector('.spaces')||document.querySelector('.hero');if(!host)return;var b=document.createElement('button');b.type='button';b.className='text recovery-entry';b.setAttribute('data-recovery-entry','1');b.textContent=txt('이미 참여했던 대화가 있나요? · 복구하기','Already joined before? · Restore');b.onclick=modal;host.appendChild(b)}
new MutationObserver(function(){setTimeout(inject,20)}).observe(document.getElementById('app'),{childList:true,subtree:true});setTimeout(inject,120);document.addEventListener('visibilitychange',function(){if(!document.hidden)setTimeout(inject,50)});
})();
