(function(){'use strict';
var SUPA='https://kacvynoegfpvgdpqtjdi.supabase.co',KEY='sb_publishable_SeG92zfrAeh5zECaVbztkw_qb0C91D6';
var timing=null,timingKey='',loading=false,timer=null,loadTimer=null,ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
function fmt(ms){var total=Math.max(0,Math.ceil(ms/60000)),h=Math.floor(total/60),m=total%60;if(ko)return h>0?h+'시간 '+m+'분':m+'분';return h>0?h+'h '+m+'m':m+'m'}
function setText(el,value){if(el&&el.textContent!==value)el.textContent=value}
function render(){var D=window.DT&&DT.state&&DT.state(),gate=document.querySelector('.next-gate');if(!D||!timing||!gate)return;var next=timing.next_round_at?new Date(timing.next_round_at):null;if(!next||isNaN(next.getTime()))return;var left=next.getTime()-Date.now();D.next_round_at=timing.next_round_at;D.can_start_next=!!timing.can_start_next||(!!timing.can_continue&&left<=0);if(D.can_start_next){if(!gate.classList.contains('schedule-open'))gate.outerHTML='<button class="btn outline full schedule-open" data-a="next">'+(ko?'다음 질문 열기 →':'Open next question →')+'</button>';return}var h=gate.querySelector('h2'),p=gate.querySelector('p');if(timing.requires_reflection){setText(h,ko?'7일 회고를 모두 마치면 이어갈 수 있어요.':'Finish the 7-day reflection to keep going.');setText(p,'')}else if(timing.schedule_mode==='calendar_day'){setText(h,ko?'다음 질문은 내일 열려요.':'The next question opens tomorrow.');setText(p,(ko?'다음 질문까지 ':'Next question in ')+fmt(left))}else{setText(h,(ko?'다음 질문까지 ':'Next question in ')+fmt(left));setText(p,'')}if(!gate.classList.contains('timing-ready'))gate.classList.add('timing-ready')}
function load(){var D=window.DT&&DT.state&&DT.state(),S=window.DT&&DT.session&&DT.session();if(!D||!S||!D.round_completed_at||(D.challenge_complete&&!D.is_premium)){timing=null;timingKey='';return}var k=S.room+':'+D.round_id+':'+(D.is_premium?'p1':'p0')+':'+(D.reflection&&D.reflection.unlocked?'r1':'r0');if(k===timingKey&&timing){render();return}if(loading)return;loading=true;fetch(SUPA+'/rest/v1/rpc/dt_get_timing',{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify({p_room_id:S.room,p_participant_token:S.token})}).then(function(r){return r.ok?r.json():null}).then(function(x){if(x){timing=x;timingKey=k;render()}}).catch(function(){}).then(function(){loading=false})}
function scheduleLoad(){if(loadTimer)clearTimeout(loadTimer);loadTimer=setTimeout(function(){loadTimer=null;load()},80)}
function start(){var app=document.getElementById('app');if(app)new MutationObserver(scheduleLoad).observe(app,{childList:true,subtree:true});timer=setInterval(function(){if(timing)render();else load()},30000);scheduleLoad()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
