(function(){'use strict';
var SUPA='https://kacvynoegfpvgdpqtjdi.supabase.co',KEY='sb_publishable_SeG92zfrAeh5zECaVbztkw_qb0C91D6';
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0,patching=false;
function copy(){return ko?{
settings:'설정',about:'About · 사용 방법',spaces:'내 대화틈',close:'닫기',title:'대화틈 사용 방법',subtitle:'같은 질문에 각자 답하고, 함께 열어보는 작은 대화 공간이에요.',
start:'시작하기',startBody:'이름을 정하고 연인·배우자·친구·가족·동료 중 관계를 선택한 뒤, 함께할 인원을 정해 초대 링크를 보내세요. 선택한 인원이 모두 들어오면 첫 질문이 시작돼요.',
guest:'회원가입 없이 시작',guestBody:'첫 대화를 시작하기 위해 이메일, 비밀번호, 회원가입이 필요하지 않아요. 이름만 입력하면 앱 내부에 익명 guest identity가 만들어져 대화 참여 정보와 연결돼요. 계정 연결은 나중에 여러 기기에서 대화를 보관하는 가치가 필요해질 때 선택할 수 있도록 확장할 예정이에요.',
free:'Free',freeBody:'2명이 7일 동안 사용할 수 있어요. 최대 2개의 대화틈을 만들 수 있고, 다음 질문은 현재 질문을 마친 뒤 다음 날 00:00에 열려요. 7일 후에도 지난 기록은 계속 볼 수 있지만 새 질문은 멈춰요.',
premium:'Premium',premiumBody:'7일 이후에도 같은 방에서 계속 대화할 수 있어요. 최대 5명, 3시간 간격의 다음 질문, 3번째 이후 방 생성, 질문 예약 기능이 포함돼요.',
reserve:'질문 예약하기',reserveBody:'Premium 방에서는 모든 참여자가 언제든 질문을 예약할 수 있어요. 예약 직후 내 질문 내용과 방 전체 queue 기준 대기 순번을 볼 수 있고, 열리기 전까지 취소할 수 있어요. 다른 사람이 예약한 질문의 내용과 작성자는 보이지 않고 방 전체 예약 개수만 보여요. 다음 라운드가 열리면 가장 먼저 예약된 질문부터 사용돼요. 직접 남긴 질문이 실제로 열리면 처음에는 누가 썼는지 숨기고, 모두 답을 연 뒤에만 작성자를 보여줘요.',
reveal:'답변 공개',revealBody:'상대의 답을 보기 전에 각자 먼저 답해요. 모두 답한 뒤에도 자동으로 공개되지 않고, ‘서로의 답 열어보기’를 직접 눌러야 해요.',
history:'지난 대화와 리듬',historyBody:'완료된 질문과 답은 지난 대화에 쌓여요. 주간·월간 리듬에서는 모두가 답을 마친 날을 확인할 수 있어요.',
notifications:'알림',notificationsBody:'새 질문이 열리거나 다른 참여자가 답을 남기면 알림을 받을 수 있도록 준비하고 있어요. 알림에는 실제 답변 내용이나 비공개 예약 질문의 내용·작성자를 넣지 않아요. 현재 서버 알림 이벤트는 적용되어 있고, 앱이 닫혀 있을 때도 도착하는 Android push는 FCM이 포함된 다음 Beta APK부터 제공될 예정이에요.',
membership:'나가기와 방 삭제',membershipBody:'일반 참여자가 나가면 본인은 이 방과 이전 기록을 더 이상 볼 수 없고 복구할 수 없어요. 남아 있는 사람에게는 함께했던 완료된 대화가 그대로 남아요. 다시 초대받으면 그 시점부터 새 멤버로 시작하고 이전 히스토리는 보이지 않아요. 방을 만든 사람이 나가면 방과 모든 기록이 모두 삭제돼요.',
day7:'7일 회고',day7Body:'7번째 질문이 끝나면 이번 주 대화를 돌아보는 회고를 함께 남겨요. Premium 방은 회고를 마친 뒤 Round 8부터 계속 이어져요.',
beta:'Private Beta',betaBody:'현재 Beta에서는 실제 결제 없이 Premium이 활성화돼요. 공개 커뮤니티 피드는 없고, private answer를 광고 타게팅에 사용하지 않으며 관계를 점수화하거나 진단하지 않아요.',
reserveLabel:'질문 예약하기',reserveSub:'떠오른 질문을 미리 남겨두세요.',leave:'이 대화틈 나가기',deleteRoom:'이 대화틈 삭제하기',leaveTitle:'정말 이 대화틈에서 나갈까요?',leaveBody:'나가면 이 대화틈과 이전 대화를 더 이상 볼 수 없고 복구할 수 없어요. 남아 있는 사람에게는 지금까지 함께한 완료된 대화가 계속 남습니다. 다시 초대받으면 그 시점부터 새로 시작해요.',deleteTitle:'이 대화틈을 삭제할까요?',deleteBody:'방을 만든 사람이 나가면 방이 삭제됩니다. 이 방의 모든 대화와 기록이 함께한 사람 모두에게서 사라지고 복구할 수 없어요.',leaveCta:'나가기',deleteCta:'대화틈 삭제',cancel:'취소',vacancy:'한 자리가 비었어요',vacancyBody:'새 멤버가 들어오면 그 시점부터 함께 대화를 시작해요. 새 멤버에게 이전 히스토리는 보이지 않아요.'
}:{
settings:'Settings',about:'About · How it works',spaces:'My spaces',close:'Close',title:'How Daehwateum works',subtitle:'A private space where everyone answers the same question separately, then opens the answers together.',
start:'Getting started',startBody:'Choose your name and a relationship type — Dating partner, Spouse, Friend, Family, or Colleague — select the room size, then share the invitation. The first question starts when everyone expected has joined.',
guest:'Start without sign-up',guestBody:'You do not need an email, password, or account to begin. Enter a name and the app creates an internal anonymous guest identity tied to your participation. Account linking may be offered later when cross-device retention provides clear value.',
free:'Free',freeBody:'Free is a 7-day experience for 2 people, with up to 2 spaces. The next question opens at 00:00 on the next calendar day after the current round is completed. After Day 7, history stays readable but new questions stop.',
premium:'Premium',premiumBody:'Premium keeps the same room going beyond Day 7. It includes rooms up to 5 people, a 3-hour next-question cadence, more than 2 spaces, and question reservations.',
reserve:'Reserve a question',reserveBody:'Anyone in a Premium room can reserve a question anytime. Right after reserving, you can see your own question and its position in the room-wide queue, and cancel it before it opens. Other people’s question text and author stay hidden; only the total queue count is shown. When the next round opens, the oldest reserved question is used first. Its author stays hidden until everyone opens the answers.',
reveal:'Opening answers',revealBody:'Everyone answers before seeing anyone else’s response. Even after everyone answers, responses stay hidden until you deliberately tap Open our answers.',
history:'History and rhythm',historyBody:'Completed conversations are saved in history. Weekly and monthly rhythm views show the days when everyone completed the conversation.',
notifications:'Notifications',notificationsBody:'Notification events are prepared when a new question opens or another participant answers. Notifications never include raw answer text or reveal a private queued question or its author. Native Android background push will arrive in the next FCM-enabled Beta APK.',
membership:'Leaving and deleting a room',membershipBody:'If a participant leaves, they lose access to the room and its history and cannot restore it. People who remain keep the completed history. If the person is invited again, they join as a new member from that point and cannot see earlier history. If the room creator leaves, the entire room and all records are deleted for everyone.',
day7:'Day 7 reflection',day7Body:'After the seventh question, everyone reflects on the week. Premium rooms continue with Round 8 after the reflection is complete.',
beta:'Private Beta',betaBody:'Premium unlocks without payment during the current beta. There is no public feed, private answers are not used for ad targeting, and Daehwateum does not score or diagnose relationships.',
reserveLabel:'Reserve a question',reserveSub:'Leave a question for later.',leave:'Leave this space',deleteRoom:'Delete this space',leaveTitle:'Leave this conversation space?',leaveBody:'You will lose access to this room and its previous conversations and cannot restore them. People who remain will keep the completed history. If you are invited again, you will start as a new member from that point.',deleteTitle:'Delete this conversation space?',deleteBody:'Because you created this room, leaving deletes the entire room. All conversations and records disappear for everyone and cannot be restored.',leaveCta:'Leave',deleteCta:'Delete space',cancel:'Cancel',vacancy:'A spot is open',vacancyBody:'When a new member joins, the conversation starts together from that point. Earlier history will not be visible to the new member.'
}}
function rpc(fn,payload){return fetch(SUPA+'/rest/v1/rpc/'+fn,{method:'POST',headers:{apikey:KEY,'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.text().then(function(t){var j=null;try{j=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw Error(j&&j.message?j.message:'Something went wrong.');return j})})}
function synthetic(a){var app=document.getElementById('app');if(!app)return;var b=document.createElement('button');b.type='button';b.setAttribute('data-a',a);b.hidden=true;app.appendChild(b);b.click();b.remove()}
function removeLocalRoom(room){try{var key='dt.spaces.v1',r=JSON.parse(localStorage.getItem(key)||'{}');if(Array.isArray(r.spaces)){r.spaces=r.spaces.filter(function(s){return s.room!==room});if(r.active===room)r.active=null;localStorage.setItem(key,JSON.stringify(r))}}catch(e){}try{var old=JSON.parse(localStorage.getItem('dt.active.v3')||'null');if(old&&old.room===room)localStorage.removeItem('dt.active.v3')}catch(e){localStorage.removeItem('dt.active.v3')}}
function fixQuestionLabels(){var c=copy();document.querySelectorAll('[data-a="custom"]').forEach(function(btn){var b=btn.querySelector('b'),s=btn.querySelector('small'),bt='✎ '+c.reserveLabel;if(b){if(b.textContent!==bt)b.textContent=bt}else if(btn.textContent!==c.reserveLabel){btn.textContent=c.reserveLabel}if(s&&s.textContent!==c.reserveSub)s.textContent=c.reserveSub})}
function fixVacancyCopy(){var D=window.DT&&DT.state&&DT.state();if(!D||D.participant_count>=D.max_participants||!(D.history&&D.history.length))return;var card=document.querySelector('.capacity-wait');if(!card)return;var c=copy(),h=card.querySelector('h2'),ps=card.querySelectorAll('p');if(h&&h.textContent!==c.vacancy)h.textContent=c.vacancy;if(ps.length&&ps[ps.length-1].textContent!==c.vacancyBody)ps[ps.length-1].textContent=c.vacancyBody}
function ensureTrigger(){var c=copy();document.querySelectorAll('.top').forEach(function(top){var b=top.querySelector('.settings-trigger')||top.querySelector('.dots'),created=false;if(!b){b=document.createElement('button');b.className='dots settings-trigger';top.appendChild(b);created=true}if(!b.classList.contains('settings-trigger'))b.classList.add('settings-trigger');if(b.hasAttribute('data-a'))b.removeAttribute('data-a');if(b.getAttribute('data-settings')!=='1')b.setAttribute('data-settings','1');if(b.getAttribute('aria-label')!==c.settings)b.setAttribute('aria-label',c.settings);if(created||b.textContent!=='⋮')b.textContent='⋮'})}
function closeMenu(){var x=document.getElementById('settings-popover');if(x)x.remove()}
function openMenu(btn){closeMenu();var c=copy(),D=window.DT&&DT.state&&DT.state(),S=window.DT&&DT.session&&DT.session(),m=document.createElement('div');m.id='settings-popover';m.className='settings-popover';var html='<button data-settings-action="about">'+c.about+'</button><button data-settings-action="spaces">'+c.spaces+'</button>';if(D&&S)html+='<button class="danger-menu" data-settings-action="leave">'+(D.me&&D.me.is_creator?c.deleteRoom:c.leave)+'</button>';m.innerHTML=html;document.body.appendChild(m);var r=btn.getBoundingClientRect();m.style.top=Math.max(56,r.bottom+6)+'px';m.style.right=Math.max(12,innerWidth-r.right)+'px'}
function openAbout(){closeMenu();var c=copy(),o=document.createElement('div');o.id='about-overlay';o.className='about-overlay';var sections=[[c.start,c.startBody],[c.guest,c.guestBody],[c.free,c.freeBody],[c.premium,c.premiumBody],[c.reserve,c.reserveBody],[c.reveal,c.revealBody],[c.history,c.historyBody],[c.notifications,c.notificationsBody],[c.membership,c.membershipBody],[c.day7,c.day7Body],[c.beta,c.betaBody]];o.innerHTML='<div class="about-sheet"><header><button class="about-back" data-about-close>←</button><b>'+c.about+'</b></header><main><span class="k">ABOUT DAEHWATEUM</span><h1>'+c.title+'</h1><p class="about-lead">'+c.subtitle+'</p>'+sections.map(function(x){return'<section><h2>'+x[0]+'</h2><p>'+x[1]+'</p></section>'}).join('')+'<button class="btn full" data-about-close>'+c.close+'</button></main></div>';document.body.appendChild(o);if(window.DT&&DT.log)DT.log('about_view',{})}
function openLeaveConfirm(){closeMenu();var D=window.DT&&DT.state&&DT.state(),S=window.DT&&DT.session&&DT.session();if(!D||!S)return;var c=copy(),creator=!!(D.me&&D.me.is_creator),o=document.createElement('div');o.id='leave-overlay';o.className='confirm-overlay';o.innerHTML='<section class="confirm-card"><span class="k">'+(creator?'DELETE ROOM':'LEAVE ROOM')+'</span><h2>'+(creator?c.deleteTitle:c.leaveTitle)+'</h2><p>'+(creator?c.deleteBody:c.leaveBody)+'</p><button class="btn full danger-btn" data-leave-confirm>'+(creator?c.deleteCta:c.leaveCta)+'</button><button class="text" data-leave-cancel>'+c.cancel+'</button></section>';document.body.appendChild(o)}
function performLeave(btn){var S=window.DT&&DT.session&&DT.session();if(!S)return;btn.disabled=true;rpc('dt_leave_room',{p_room_id:S.room,p_participant_token:S.token}).then(function(){removeLocalRoom(S.room);location.replace(window.DT&&DT.base?DT.base():location.pathname)}).catch(function(e){btn.disabled=false;alert(e.message)})}
function patch(){if(patching)return;patching=true;requestAnimationFrame(function(){patching=false;fixQuestionLabels();fixVacancyCopy();ensureTrigger()})}
document.addEventListener('click',function(e){var t=e.target.closest&&e.target.closest('[data-settings]');if(t){e.preventDefault();e.stopImmediatePropagation();openMenu(t);return}var a=e.target.closest&&e.target.closest('[data-settings-action]');if(a){e.preventDefault();var v=a.getAttribute('data-settings-action');if(v==='about')openAbout();else if(v==='spaces'){closeMenu();synthetic('home')}else if(v==='leave')openLeaveConfirm();return}if(e.target.closest&&e.target.closest('[data-about-close]')){e.preventDefault();var o=document.getElementById('about-overlay');if(o)o.remove();return}if(e.target.closest&&e.target.closest('[data-leave-cancel]')){e.preventDefault();var l=document.getElementById('leave-overlay');if(l)l.remove();return}var confirmBtn=e.target.closest&&e.target.closest('[data-leave-confirm]');if(confirmBtn){e.preventDefault();performLeave(confirmBtn);return}if(!e.target.closest||!e.target.closest('#settings-popover'))closeMenu()},true);
function start(){var app=document.getElementById('app');if(app)new MutationObserver(patch).observe(app,{childList:true,subtree:true});var old=window.DaehwateumBack;window.DaehwateumBack=function(){var l=document.getElementById('leave-overlay');if(l){l.remove();return true}var o=document.getElementById('about-overlay');if(o){o.remove();return true}var m=document.getElementById('settings-popover');if(m){m.remove();return true}return old?old():false};patch()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
