(function(){'use strict';
var SUPA='https://kacvynoegfpvgdpqtjdi.supabase.co';
var GUEST_KEY='dt.guest.v1';
var ANDROID_PENDING='dt.android.pendingInviteClaim.v66';
var CLAIM_CLIPBOARD_PREFIX='DAEHWATEUM_INVITE:dtclaim_';
var p=new URLSearchParams(location.search);
var token=p.get('invite')||'';
var claim=p.get('claim')||'';
if(location.hash){try{var hp=new URLSearchParams(location.hash.replace(/^#\??/,''));if(!token)token=hp.get('invite')||'';if(!claim)claim=hp.get('claim')||''}catch(e){}}
var ko=(navigator.language||'ko').toLowerCase().indexOf('ko')===0;
var ua=navigator.userAgent||'';
var android=/Android/i.test(ua);
var ios=/iPad|iPhone|iPod/.test(ua)||(navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1);
var mobile=android||ios||/Mobile/i.test(ua)||navigator.maxTouchPoints>1;
var kakao=/KAKAOTALK/i.test(ua);
var standalone=navigator.standalone===true||(window.matchMedia&&window.matchMedia('(display-mode: standalone)').matches);
var loading=document.getElementById('loading'),invite=document.getElementById('invite'),continuation=document.getElementById('continue'),closed=document.getElementById('closed');
var title=document.getElementById('title'),body=document.getElementById('body'),open=document.getElementById('open'),closedTitle=document.getElementById('closedTitle'),closedBody=document.getElementById('closedBody');
var continueTitle=document.getElementById('continueTitle'),continueBody=document.getElementById('continueBody'),continueOpen=document.getElementById('continueOpen'),continueWeb=document.getElementById('continueWeb');
var appInstall=document.getElementById('appInstall'),installHelp=document.getElementById('installHelp'),installClose=document.getElementById('installClose'),installKind=document.getElementById('installKind'),installTitle=document.getElementById('installTitle'),installLead=document.getElementById('installLead'),installStep1=document.getElementById('installStep1'),installStep2=document.getElementById('installStep2'),installStep3=document.getElementById('installStep3');

function uuid(){if(window.crypto&&typeof crypto.randomUUID==='function')return crypto.randomUUID();var a=new Uint8Array(16);if(window.crypto&&crypto.getRandomValues)crypto.getRandomValues(a);else for(var i=0;i<16;i++)a[i]=Math.floor(Math.random()*256);a[6]=(a[6]&15)|64;a[8]=(a[8]&63)|128;return Array.prototype.map.call(a,function(b,i){return([4,6,8,10].indexOf(i)>=0?'-':'')+b.toString(16).padStart(2,'0')}).join('')}
function guestId(){var id='';try{id=localStorage.getItem(GUEST_KEY)||''}catch(e){}if(!/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(id)){id=uuid();try{localStorage.setItem(GUEST_KEY,id)}catch(e){}}return id}
function rpc(fn,payload){return fetch(SUPA+'/rest/v1/rpc/'+fn,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)}).then(function(r){return r.text().then(function(t){var j=null;try{j=t?JSON.parse(t):null}catch(e){}if(!r.ok)throw Error(j&&j.message?j.message:'Request failed');return j})})}
function hideAll(){loading.classList.add('hidden');invite.classList.add('hidden');continuation.classList.add('hidden');closed.classList.add('hidden');appInstall.classList.add('hidden');continueWeb.classList.add('hidden')}
function showClosed(h,b){hideAll();closed.classList.remove('hidden');closedTitle.textContent=h;closedBody.textContent=b}
function webUrl(){return '../?claim='+encodeURIComponent(claim)+'&web=1'}
function androidDeepLink(){return 'daehwateum://join?invite='+encodeURIComponent('dtclaim_'+(claim||''))}
function hideInstallHelp(){installHelp.classList.add('hidden')}
function rememberClaim(){if(!claim)return;try{localStorage.setItem('dt.pending.inviteClaim.v66',claim)}catch(e){}}
function persistClaimInUrl(){if(!claim)return;try{history.replaceState({},'',location.pathname+'?claim='+encodeURIComponent(claim))}catch(e){}}
function copyClaimHandoff(){if(!claim)return;var payload=CLAIM_CLIPBOARD_PREFIX+claim;try{var el=document.createElement('textarea');el.value=payload;el.setAttribute('readonly','');el.style.position='fixed';el.style.opacity='0';el.style.pointerEvents='none';document.body.appendChild(el);el.select();document.execCommand('copy');document.body.removeChild(el)}catch(e){}try{if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(payload).catch(function(){})}catch(e){}}
function beginAndroidInstall(){if(!claim)return;copyClaimHandoff();rememberClaim();try{sessionStorage.setItem(ANDROID_PENDING,claim)}catch(e){}appInstall.textContent=ko?'다운로드 중 · 설치 후 이 초대로 이어져요':'Downloading · this invite will continue after install';location.href='../downloads/daehwateum-beta.apk'}
function resumeAndroidInstall(){if(!android||document.hidden||!claim)return;var pending='';try{pending=sessionStorage.getItem(ANDROID_PENDING)||''}catch(e){}if(pending!==claim)return;try{sessionStorage.removeItem(ANDROID_PENDING)}catch(e){}setTimeout(function(){location.href=androidDeepLink()},250)}
function openAndroidApp(){rememberClaim();location.href=androidDeepLink()}
function openWeb(){rememberClaim();location.href=webUrl()}
function configureInstallAfterClaim(){appInstall.classList.add('hidden');continueWeb.classList.add('hidden');if(!mobile||standalone)return;if(android){continueOpen.textContent=ko?'대화틈 앱 열기':'Open Daehwateum app';continueOpen.onclick=openAndroidApp;appInstall.textContent=ko?'대화틈 앱 다운로드':'Download Daehwateum app';appInstall.onclick=beginAndroidInstall;appInstall.classList.remove('hidden');continueWeb.textContent=ko?'웹에서 계속하기':'Continue on the web';continueWeb.onclick=openWeb;continueWeb.classList.remove('hidden');return}continueOpen.textContent=ko?'대화틈에서 계속하기':'Continue in Daehwateum';continueOpen.onclick=openWeb;appInstall.textContent=ko?'홈 화면에 추가하기':'Add to Home Screen';appInstall.classList.remove('hidden');installKind.textContent='IPHONE';installTitle.textContent=ko?'대화틈을 홈 화면에 추가하기':'Add Daehwateum to your Home Screen';installLead.textContent=ko?'초대는 이미 저장됐어요. 브라우저가 바뀌어도 아래 저장된 초대 링크로 다시 이어갈 수 있어요.':'Your invite is already saved. You can resume it even after switching browser context.';if(kakao){installStep1.textContent=ko?'카카오톡의 ··· 메뉴에서 ‘다른 브라우저로 열기’를 선택해 Safari로 여세요.':'In KakaoTalk, use the ··· menu and choose “Open in another browser” to open Safari.';installStep2.textContent=ko?'Safari에서 ‘대화틈에서 계속하기’를 눌러 저장된 초대로 들어가세요.':'In Safari, tap “Continue in Daehwateum” to open the saved invite.'}else{installStep1.textContent=ko?'Safari에서 이 저장된 초대 화면을 열어주세요.':'Open this saved-invite page in Safari.';installStep2.textContent=ko?'‘대화틈에서 계속하기’를 눌러 대화 화면으로 이동하세요.':'Tap “Continue in Daehwateum” to open the conversation.'}installStep3.textContent=ko?'Safari 공유 버튼 → ‘홈 화면에 추가’를 선택하세요.':'Tap Safari Share → “Add to Home Screen”.';appInstall.onclick=function(){installHelp.classList.remove('hidden')}}
function showInvite(status){hideAll();invite.classList.remove('hidden');var inviter=status&&status.inviter_name?String(status.inviter_name).trim():'';if(ko){title.textContent=inviter?inviter+'님이 대화틈에 초대했어요.':'대화틈에 초대받았어요.';body.innerHTML='하루에 질문 하나.<br>서로 답한 뒤, 함께 열어봐요.';open.textContent='초대받기'}else{title.textContent=inviter?inviter+' invited you to Daehwateum.':'You were invited to Daehwateum.';body.innerHTML='One question at a time.<br>Answer separately, then open together.';open.textContent='Accept invite'}open.disabled=false;open.onclick=acceptInvite}
function showContinue(status){hideAll();continuation.classList.remove('hidden');rememberClaim();persistClaimInUrl();var inviter=status&&status.inviter_name?String(status.inviter_name).trim():'';if(ko){continueTitle.textContent='초대를 저장했어요.';continueBody.innerHTML=(inviter?inviter+'님과의 ':'')+'대화틈에서 계속할까요?<br><span>홈 화면에 추가하면 더 편하게 사용할 수 있어요.</span>'}else{continueTitle.textContent='Your invite is saved.';continueBody.innerHTML='Continue in Daehwateum?<br><span>Add it to your Home Screen for easier access.</span>'}continueOpen.textContent=ko?'대화틈에서 계속하기':'Continue in Daehwateum';continueOpen.onclick=openWeb;configureInstallAfterClaim()}
function acceptInvite(){if(!token||open.disabled)return;open.disabled=true;open.textContent=ko?'초대를 저장하고 있어요…':'Saving invite…';rpc('dt_claim_invite',{p_invite_token:token,p_app_user_id:guestId()}).then(function(r){if(!r||!r.claim_token)throw Error('Could not save invite');claim=String(r.claim_token).toLowerCase();token='';showContinue(r)}).catch(function(e){open.disabled=false;open.textContent=ko?'초대받기':'Accept invite';showClosed(ko?'초대를 저장하지 못했어요.':'Could not save this invite.',e&&e.message?e.message:(ko?'잠시 후 다시 시도해 주세요.':'Please try again.'))})}
function loadInvite(){if(!token){showClosed(ko?'초대 정보가 없어요.':'Invite not found.',ko?'전달받은 링크를 다시 확인해 주세요.':'Please check the invitation link.');return}rpc('dt_get_invite_status',{p_invite_token:token}).then(function(s){if(!s||!s.valid){showClosed(ko?'이 초대는 더 이상 열 수 없어요.':'This invite is no longer available.',ko?'링크가 만료되었거나 유효하지 않아요.':'The link has expired or is invalid.');return}if(s.full){showClosed(ko?'이 대화틈은 참여가 완료됐어요.':'This conversation space is full.',ko?'이미 참여했다면 기존 대화틈에서 이어서 사용할 수 있어요.':'If you already joined, continue from your existing Daehwateum.');return}showInvite(s)}).catch(function(){showClosed(ko?'초대장을 확인하지 못했어요.':'Could not check this invite.',ko?'잠시 후 다시 링크를 열어 주세요.':'Please open the link again in a moment.')})}
function loadClaim(){if(!/^[0-9a-f]{48}$/i.test(claim)){showClosed(ko?'저장된 초대 정보가 올바르지 않아요.':'Saved invite not found.',ko?'원래 초대 링크를 다시 열어 주세요.':'Please open the original invitation link again.');return}claim=claim.toLowerCase();rpc('dt_get_invite_claim_status',{p_claim_token:claim}).then(function(s){if(!s||!s.valid){var msg=s&&s.accepted?(ko?'이 초대는 이미 사용됐어요. 기존 대화틈에서 이어서 사용해 주세요.':'This invite was already used. Continue from your existing Daehwateum.'):(ko?'저장된 초대가 만료되었어요. 원래 초대 링크를 다시 열어 주세요.':'The saved invite expired. Open the original invitation again.');showClosed(ko?'이 초대를 이어갈 수 없어요.':'This invite can’t be resumed.',msg);return}if(s.full){showClosed(ko?'이 대화틈은 참여가 완료됐어요.':'This conversation space is full.',ko?'이미 참여했다면 기존 대화틈에서 이어서 사용할 수 있어요.':'If you already joined, continue from your existing Daehwateum.');return}showContinue(s)}).catch(function(){showClosed(ko?'저장된 초대를 확인하지 못했어요.':'Could not check the saved invite.',ko?'잠시 후 다시 열어 주세요.':'Please try again in a moment.')})}

if(!ko){document.documentElement.lang='en';document.querySelector('.brand-name').textContent='Daehwateum';document.querySelector('.steps').innerHTML='<div class="step">One question</div><div class="step">Answer separately</div><div class="step">Open together</div>';document.querySelector('.fine').textContent='No account required.';installClose.setAttribute('aria-label','Close')}
installClose.onclick=hideInstallHelp;installHelp.addEventListener('click',function(e){if(e.target===installHelp)hideInstallHelp()});document.addEventListener('visibilitychange',function(){if(!document.hidden)resumeAndroidInstall()});window.addEventListener('focus',resumeAndroidInstall);
if(claim)loadClaim();else loadInvite();
})();
